language: node_js

node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  VERSION: "$TRAVIS_BUILD_NUMBER"

before_install:
  - yarn

script:
  - yarn test:unit
  - yarn test:integration

after_success:
  - yarn semantic-release
  