language: node_js
node_js:
  - '12'

branches:
  only:
    - main

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  VERSION: '$TRAVIS_BUILD_NUMBER'

before_install:
  - yarn

before_script:
  - yarn server &

script:
  - yarn lint
  - yarn test:unit
  - yarn test:integration

after_success:
  - yarn run semantic-release
